name: url-shortner

services:
  link-service:
    build:
      context: .
      dockerfile: Dockerfile.service
    depends_on:
      link-service-db:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - '${APP_PORT}'
    networks:
      - url-shortner-network
      - link-service-db-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'link-service:${APP_PORT}']
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

  link-service-db:
    build:
      context: .
      dockerfile: Dockerfile.db
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_PORT: ${DB_PORT}
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - link-service-db-network
    volumes:
      - link-service-db-data:/var/dto/db/data
    healthcheck:
      test: bash -c "dockerize -wait tcp://localhost:${DB_PORT} -timeout 5s"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  url-shortner-network:
    external: true
  link-service-db-network:

volumes:
  link-service-db-data:
